/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: auth.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "auth.pb-c.h"
void   authpb__user__init
                     (Authpb__User         *message)
{
  static Authpb__User init_value = AUTHPB__USER__INIT;
  *message = init_value;
}
size_t authpb__user__get_packed_size
                     (const Authpb__User *message)
{
  assert(message->base.descriptor == &authpb__user__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t authpb__user__pack
                     (const Authpb__User *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &authpb__user__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t authpb__user__pack_to_buffer
                     (const Authpb__User *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &authpb__user__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Authpb__User *
       authpb__user__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Authpb__User *)
     protobuf_c_message_unpack (&authpb__user__descriptor,
                                allocator, len, data);
}
void   authpb__user__free_unpacked
                     (Authpb__User *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &authpb__user__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   authpb__permission__init
                     (Authpb__Permission         *message)
{
  static Authpb__Permission init_value = AUTHPB__PERMISSION__INIT;
  *message = init_value;
}
size_t authpb__permission__get_packed_size
                     (const Authpb__Permission *message)
{
  assert(message->base.descriptor == &authpb__permission__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t authpb__permission__pack
                     (const Authpb__Permission *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &authpb__permission__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t authpb__permission__pack_to_buffer
                     (const Authpb__Permission *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &authpb__permission__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Authpb__Permission *
       authpb__permission__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Authpb__Permission *)
     protobuf_c_message_unpack (&authpb__permission__descriptor,
                                allocator, len, data);
}
void   authpb__permission__free_unpacked
                     (Authpb__Permission *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &authpb__permission__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   authpb__role__init
                     (Authpb__Role         *message)
{
  static Authpb__Role init_value = AUTHPB__ROLE__INIT;
  *message = init_value;
}
size_t authpb__role__get_packed_size
                     (const Authpb__Role *message)
{
  assert(message->base.descriptor == &authpb__role__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t authpb__role__pack
                     (const Authpb__Role *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &authpb__role__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t authpb__role__pack_to_buffer
                     (const Authpb__Role *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &authpb__role__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Authpb__Role *
       authpb__role__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Authpb__Role *)
     protobuf_c_message_unpack (&authpb__role__descriptor,
                                allocator, len, data);
}
void   authpb__role__free_unpacked
                     (Authpb__Role *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &authpb__role__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor authpb__user__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Authpb__User, has_name),
    offsetof(Authpb__User, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "password",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Authpb__User, has_password),
    offsetof(Authpb__User, password),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "roles",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Authpb__User, n_roles),
    offsetof(Authpb__User, roles),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned authpb__user__field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = password */
  2,   /* field[2] = roles */
};
static const ProtobufCIntRange authpb__user__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor authpb__user__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "authpb.User",
  "User",
  "Authpb__User",
  "authpb",
  sizeof(Authpb__User),
  3,
  authpb__user__field_descriptors,
  authpb__user__field_indices_by_name,
  1,  authpb__user__number_ranges,
  (ProtobufCMessageInit) authpb__user__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue authpb__permission__type__enum_values_by_number[3] =
{
  { "READ", "AUTHPB__PERMISSION__TYPE__READ", 0 },
  { "WRITE", "AUTHPB__PERMISSION__TYPE__WRITE", 1 },
  { "READWRITE", "AUTHPB__PERMISSION__TYPE__READWRITE", 2 },
};
static const ProtobufCIntRange authpb__permission__type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex authpb__permission__type__enum_values_by_name[3] =
{
  { "READ", 0 },
  { "READWRITE", 2 },
  { "WRITE", 1 },
};
const ProtobufCEnumDescriptor authpb__permission__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "authpb.Permission.Type",
  "Type",
  "Authpb__Permission__Type",
  "authpb",
  3,
  authpb__permission__type__enum_values_by_number,
  3,
  authpb__permission__type__enum_values_by_name,
  1,
  authpb__permission__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor authpb__permission__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Authpb__Permission, has_key),
    offsetof(Authpb__Permission, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "permType",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Authpb__Permission, has_permtype),
    offsetof(Authpb__Permission, permtype),
    &authpb__permission__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned authpb__permission__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = permType */
};
static const ProtobufCIntRange authpb__permission__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor authpb__permission__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "authpb.Permission",
  "Permission",
  "Authpb__Permission",
  "authpb",
  sizeof(Authpb__Permission),
  2,
  authpb__permission__field_descriptors,
  authpb__permission__field_indices_by_name,
  1,  authpb__permission__number_ranges,
  (ProtobufCMessageInit) authpb__permission__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor authpb__role__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Authpb__Role, has_name),
    offsetof(Authpb__Role, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "keyPermission",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Authpb__Role, n_keypermission),
    offsetof(Authpb__Role, keypermission),
    &authpb__permission__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned authpb__role__field_indices_by_name[] = {
  1,   /* field[1] = keyPermission */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange authpb__role__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor authpb__role__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "authpb.Role",
  "Role",
  "Authpb__Role",
  "authpb",
  sizeof(Authpb__Role),
  2,
  authpb__role__field_descriptors,
  authpb__role__field_indices_by_name,
  1,  authpb__role__number_ranges,
  (ProtobufCMessageInit) authpb__role__init,
  NULL,NULL,NULL    /* reserved[123] */
};
