/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: d21.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "d21.pb-c.h"
void   pb__tx_begin_request__init
                     (Pb__TxBeginRequest         *message)
{
  static Pb__TxBeginRequest init_value = PB__TX_BEGIN_REQUEST__INIT;
  *message = init_value;
}
size_t pb__tx_begin_request__get_packed_size
                     (const Pb__TxBeginRequest *message)
{
  assert(message->base.descriptor == &pb__tx_begin_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb__tx_begin_request__pack
                     (const Pb__TxBeginRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb__tx_begin_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb__tx_begin_request__pack_to_buffer
                     (const Pb__TxBeginRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb__tx_begin_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pb__TxBeginRequest *
       pb__tx_begin_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pb__TxBeginRequest *)
     protobuf_c_message_unpack (&pb__tx_begin_request__descriptor,
                                allocator, len, data);
}
void   pb__tx_begin_request__free_unpacked
                     (Pb__TxBeginRequest *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &pb__tx_begin_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pb__tx_begin_response__init
                     (Pb__TxBeginResponse         *message)
{
  static Pb__TxBeginResponse init_value = PB__TX_BEGIN_RESPONSE__INIT;
  *message = init_value;
}
size_t pb__tx_begin_response__get_packed_size
                     (const Pb__TxBeginResponse *message)
{
  assert(message->base.descriptor == &pb__tx_begin_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb__tx_begin_response__pack
                     (const Pb__TxBeginResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb__tx_begin_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb__tx_begin_response__pack_to_buffer
                     (const Pb__TxBeginResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb__tx_begin_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pb__TxBeginResponse *
       pb__tx_begin_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pb__TxBeginResponse *)
     protobuf_c_message_unpack (&pb__tx_begin_response__descriptor,
                                allocator, len, data);
}
void   pb__tx_begin_response__free_unpacked
                     (Pb__TxBeginResponse *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &pb__tx_begin_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pb__tx_commit_request__init
                     (Pb__TxCommitRequest         *message)
{
  static Pb__TxCommitRequest init_value = PB__TX_COMMIT_REQUEST__INIT;
  *message = init_value;
}
size_t pb__tx_commit_request__get_packed_size
                     (const Pb__TxCommitRequest *message)
{
  assert(message->base.descriptor == &pb__tx_commit_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb__tx_commit_request__pack
                     (const Pb__TxCommitRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb__tx_commit_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb__tx_commit_request__pack_to_buffer
                     (const Pb__TxCommitRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb__tx_commit_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pb__TxCommitRequest *
       pb__tx_commit_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pb__TxCommitRequest *)
     protobuf_c_message_unpack (&pb__tx_commit_request__descriptor,
                                allocator, len, data);
}
void   pb__tx_commit_request__free_unpacked
                     (Pb__TxCommitRequest *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &pb__tx_commit_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pb__tx_commit_response__init
                     (Pb__TxCommitResponse         *message)
{
  static Pb__TxCommitResponse init_value = PB__TX_COMMIT_RESPONSE__INIT;
  *message = init_value;
}
size_t pb__tx_commit_response__get_packed_size
                     (const Pb__TxCommitResponse *message)
{
  assert(message->base.descriptor == &pb__tx_commit_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb__tx_commit_response__pack
                     (const Pb__TxCommitResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb__tx_commit_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb__tx_commit_response__pack_to_buffer
                     (const Pb__TxCommitResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb__tx_commit_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pb__TxCommitResponse *
       pb__tx_commit_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pb__TxCommitResponse *)
     protobuf_c_message_unpack (&pb__tx_commit_response__descriptor,
                                allocator, len, data);
}
void   pb__tx_commit_response__free_unpacked
                     (Pb__TxCommitResponse *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &pb__tx_commit_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pb__tx_rollback_request__init
                     (Pb__TxRollbackRequest         *message)
{
  static Pb__TxRollbackRequest init_value = PB__TX_ROLLBACK_REQUEST__INIT;
  *message = init_value;
}
size_t pb__tx_rollback_request__get_packed_size
                     (const Pb__TxRollbackRequest *message)
{
  assert(message->base.descriptor == &pb__tx_rollback_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb__tx_rollback_request__pack
                     (const Pb__TxRollbackRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb__tx_rollback_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb__tx_rollback_request__pack_to_buffer
                     (const Pb__TxRollbackRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb__tx_rollback_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pb__TxRollbackRequest *
       pb__tx_rollback_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pb__TxRollbackRequest *)
     protobuf_c_message_unpack (&pb__tx_rollback_request__descriptor,
                                allocator, len, data);
}
void   pb__tx_rollback_request__free_unpacked
                     (Pb__TxRollbackRequest *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &pb__tx_rollback_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pb__tx_rollback_response__init
                     (Pb__TxRollbackResponse         *message)
{
  static Pb__TxRollbackResponse init_value = PB__TX_ROLLBACK_RESPONSE__INIT;
  *message = init_value;
}
size_t pb__tx_rollback_response__get_packed_size
                     (const Pb__TxRollbackResponse *message)
{
  assert(message->base.descriptor == &pb__tx_rollback_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb__tx_rollback_response__pack
                     (const Pb__TxRollbackResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb__tx_rollback_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb__tx_rollback_response__pack_to_buffer
                     (const Pb__TxRollbackResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb__tx_rollback_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pb__TxRollbackResponse *
       pb__tx_rollback_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pb__TxRollbackResponse *)
     protobuf_c_message_unpack (&pb__tx_rollback_response__descriptor,
                                allocator, len, data);
}
void   pb__tx_rollback_response__free_unpacked
                     (Pb__TxRollbackResponse *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &pb__tx_rollback_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pb__request__init
                     (Pb__Request         *message)
{
  static Pb__Request init_value = PB__REQUEST__INIT;
  *message = init_value;
}
size_t pb__request__get_packed_size
                     (const Pb__Request *message)
{
  assert(message->base.descriptor == &pb__request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb__request__pack
                     (const Pb__Request *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb__request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb__request__pack_to_buffer
                     (const Pb__Request *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb__request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pb__Request *
       pb__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pb__Request *)
     protobuf_c_message_unpack (&pb__request__descriptor,
                                allocator, len, data);
}
void   pb__request__free_unpacked
                     (Pb__Request *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &pb__request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pb__tx_request__init
                     (Pb__TxRequest         *message)
{
  static Pb__TxRequest init_value = PB__TX_REQUEST__INIT;
  *message = init_value;
}
size_t pb__tx_request__get_packed_size
                     (const Pb__TxRequest *message)
{
  assert(message->base.descriptor == &pb__tx_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb__tx_request__pack
                     (const Pb__TxRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb__tx_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb__tx_request__pack_to_buffer
                     (const Pb__TxRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb__tx_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pb__TxRequest *
       pb__tx_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pb__TxRequest *)
     protobuf_c_message_unpack (&pb__tx_request__descriptor,
                                allocator, len, data);
}
void   pb__tx_request__free_unpacked
                     (Pb__TxRequest *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &pb__tx_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pb__tx_response__init
                     (Pb__TxResponse         *message)
{
  static Pb__TxResponse init_value = PB__TX_RESPONSE__INIT;
  *message = init_value;
}
size_t pb__tx_response__get_packed_size
                     (const Pb__TxResponse *message)
{
  assert(message->base.descriptor == &pb__tx_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb__tx_response__pack
                     (const Pb__TxResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb__tx_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb__tx_response__pack_to_buffer
                     (const Pb__TxResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb__tx_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pb__TxResponse *
       pb__tx_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pb__TxResponse *)
     protobuf_c_message_unpack (&pb__tx_response__descriptor,
                                allocator, len, data);
}
void   pb__tx_response__free_unpacked
                     (Pb__TxResponse *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &pb__tx_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pb__control_type_string__init
                     (Pb__ControlTypeString         *message)
{
  static Pb__ControlTypeString init_value = PB__CONTROL_TYPE_STRING__INIT;
  *message = init_value;
}
size_t pb__control_type_string__get_packed_size
                     (const Pb__ControlTypeString *message)
{
  assert(message->base.descriptor == &pb__control_type_string__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb__control_type_string__pack
                     (const Pb__ControlTypeString *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb__control_type_string__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb__control_type_string__pack_to_buffer
                     (const Pb__ControlTypeString *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb__control_type_string__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pb__ControlTypeString *
       pb__control_type_string__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pb__ControlTypeString *)
     protobuf_c_message_unpack (&pb__control_type_string__descriptor,
                                allocator, len, data);
}
void   pb__control_type_string__free_unpacked
                     (Pb__ControlTypeString *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &pb__control_type_string__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pb__entry__init
                     (Pb__Entry         *message)
{
  static Pb__Entry init_value = PB__ENTRY__INIT;
  *message = init_value;
}
size_t pb__entry__get_packed_size
                     (const Pb__Entry *message)
{
  assert(message->base.descriptor == &pb__entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb__entry__pack
                     (const Pb__Entry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb__entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb__entry__pack_to_buffer
                     (const Pb__Entry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb__entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pb__Entry *
       pb__entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pb__Entry *)
     protobuf_c_message_unpack (&pb__entry__descriptor,
                                allocator, len, data);
}
void   pb__entry__free_unpacked
                     (Pb__Entry *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &pb__entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pb__entry_attribute__init
                     (Pb__EntryAttribute         *message)
{
  static Pb__EntryAttribute init_value = PB__ENTRY_ATTRIBUTE__INIT;
  *message = init_value;
}
size_t pb__entry_attribute__get_packed_size
                     (const Pb__EntryAttribute *message)
{
  assert(message->base.descriptor == &pb__entry_attribute__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb__entry_attribute__pack
                     (const Pb__EntryAttribute *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb__entry_attribute__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb__entry_attribute__pack_to_buffer
                     (const Pb__EntryAttribute *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb__entry_attribute__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pb__EntryAttribute *
       pb__entry_attribute__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pb__EntryAttribute *)
     protobuf_c_message_unpack (&pb__entry_attribute__descriptor,
                                allocator, len, data);
}
void   pb__entry_attribute__free_unpacked
                     (Pb__EntryAttribute *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &pb__entry_attribute__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pb__response__init
                     (Pb__Response         *message)
{
  static Pb__Response init_value = PB__RESPONSE__INIT;
  *message = init_value;
}
size_t pb__response__get_packed_size
                     (const Pb__Response *message)
{
  assert(message->base.descriptor == &pb__response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb__response__pack
                     (const Pb__Response *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb__response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb__response__pack_to_buffer
                     (const Pb__Response *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb__response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pb__Response *
       pb__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pb__Response *)
     protobuf_c_message_unpack (&pb__response__descriptor,
                                allocator, len, data);
}
void   pb__response__free_unpacked
                     (Pb__Response *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &pb__response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pb__metadata__init
                     (Pb__Metadata         *message)
{
  static Pb__Metadata init_value = PB__METADATA__INIT;
  *message = init_value;
}
size_t pb__metadata__get_packed_size
                     (const Pb__Metadata *message)
{
  assert(message->base.descriptor == &pb__metadata__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb__metadata__pack
                     (const Pb__Metadata *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb__metadata__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb__metadata__pack_to_buffer
                     (const Pb__Metadata *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb__metadata__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pb__Metadata *
       pb__metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pb__Metadata *)
     protobuf_c_message_unpack (&pb__metadata__descriptor,
                                allocator, len, data);
}
void   pb__metadata__free_unpacked
                     (Pb__Metadata *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &pb__metadata__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor pb__tx_begin_request__field_descriptors[1] =
{
  {
    "ID",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Pb__TxBeginRequest, has_id),
    offsetof(Pb__TxBeginRequest, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb__tx_begin_request__field_indices_by_name[] = {
  0,   /* field[0] = ID */
};
static const ProtobufCIntRange pb__tx_begin_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor pb__tx_begin_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb.TxBeginRequest",
  "TxBeginRequest",
  "Pb__TxBeginRequest",
  "pb",
  sizeof(Pb__TxBeginRequest),
  1,
  pb__tx_begin_request__field_descriptors,
  pb__tx_begin_request__field_indices_by_name,
  1,  pb__tx_begin_request__number_ranges,
  (ProtobufCMessageInit) pb__tx_begin_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pb__tx_begin_response__field_descriptors[3] =
{
  {
    "TID",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Pb__TxBeginResponse, has_tid),
    offsetof(Pb__TxBeginResponse, tid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Metadata",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Pb__TxBeginResponse, metadata),
    &pb__metadata__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ID",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Pb__TxBeginResponse, has_id),
    offsetof(Pb__TxBeginResponse, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb__tx_begin_response__field_indices_by_name[] = {
  2,   /* field[2] = ID */
  1,   /* field[1] = Metadata */
  0,   /* field[0] = TID */
};
static const ProtobufCIntRange pb__tx_begin_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor pb__tx_begin_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb.TxBeginResponse",
  "TxBeginResponse",
  "Pb__TxBeginResponse",
  "pb",
  sizeof(Pb__TxBeginResponse),
  3,
  pb__tx_begin_response__field_descriptors,
  pb__tx_begin_response__field_indices_by_name,
  1,  pb__tx_begin_response__number_ranges,
  (ProtobufCMessageInit) pb__tx_begin_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pb__tx_commit_request__field_descriptors[2] =
{
  {
    "TID",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Pb__TxCommitRequest, has_tid),
    offsetof(Pb__TxCommitRequest, tid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ID",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Pb__TxCommitRequest, has_id),
    offsetof(Pb__TxCommitRequest, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb__tx_commit_request__field_indices_by_name[] = {
  1,   /* field[1] = ID */
  0,   /* field[0] = TID */
};
static const ProtobufCIntRange pb__tx_commit_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor pb__tx_commit_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb.TxCommitRequest",
  "TxCommitRequest",
  "Pb__TxCommitRequest",
  "pb",
  sizeof(Pb__TxCommitRequest),
  2,
  pb__tx_commit_request__field_descriptors,
  pb__tx_commit_request__field_indices_by_name,
  1,  pb__tx_commit_request__number_ranges,
  (ProtobufCMessageInit) pb__tx_commit_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pb__tx_commit_response__field_descriptors[3] =
{
  {
    "TID",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Pb__TxCommitResponse, has_tid),
    offsetof(Pb__TxCommitResponse, tid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Metadata",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Pb__TxCommitResponse, metadata),
    &pb__metadata__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ID",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Pb__TxCommitResponse, has_id),
    offsetof(Pb__TxCommitResponse, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb__tx_commit_response__field_indices_by_name[] = {
  2,   /* field[2] = ID */
  1,   /* field[1] = Metadata */
  0,   /* field[0] = TID */
};
static const ProtobufCIntRange pb__tx_commit_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor pb__tx_commit_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb.TxCommitResponse",
  "TxCommitResponse",
  "Pb__TxCommitResponse",
  "pb",
  sizeof(Pb__TxCommitResponse),
  3,
  pb__tx_commit_response__field_descriptors,
  pb__tx_commit_response__field_indices_by_name,
  1,  pb__tx_commit_response__number_ranges,
  (ProtobufCMessageInit) pb__tx_commit_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pb__tx_rollback_request__field_descriptors[2] =
{
  {
    "TID",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Pb__TxRollbackRequest, has_tid),
    offsetof(Pb__TxRollbackRequest, tid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ID",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Pb__TxRollbackRequest, has_id),
    offsetof(Pb__TxRollbackRequest, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb__tx_rollback_request__field_indices_by_name[] = {
  1,   /* field[1] = ID */
  0,   /* field[0] = TID */
};
static const ProtobufCIntRange pb__tx_rollback_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor pb__tx_rollback_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb.TxRollbackRequest",
  "TxRollbackRequest",
  "Pb__TxRollbackRequest",
  "pb",
  sizeof(Pb__TxRollbackRequest),
  2,
  pb__tx_rollback_request__field_descriptors,
  pb__tx_rollback_request__field_indices_by_name,
  1,  pb__tx_rollback_request__number_ranges,
  (ProtobufCMessageInit) pb__tx_rollback_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pb__tx_rollback_response__field_descriptors[3] =
{
  {
    "TID",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Pb__TxRollbackResponse, has_tid),
    offsetof(Pb__TxRollbackResponse, tid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Metadata",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Pb__TxRollbackResponse, metadata),
    &pb__metadata__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ID",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Pb__TxRollbackResponse, has_id),
    offsetof(Pb__TxRollbackResponse, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb__tx_rollback_response__field_indices_by_name[] = {
  2,   /* field[2] = ID */
  1,   /* field[1] = Metadata */
  0,   /* field[0] = TID */
};
static const ProtobufCIntRange pb__tx_rollback_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor pb__tx_rollback_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb.TxRollbackResponse",
  "TxRollbackResponse",
  "Pb__TxRollbackResponse",
  "pb",
  sizeof(Pb__TxRollbackResponse),
  3,
  pb__tx_rollback_response__field_descriptors,
  pb__tx_rollback_response__field_indices_by_name,
  1,  pb__tx_rollback_response__number_ranges,
  (ProtobufCMessageInit) pb__tx_rollback_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pb__request__field_descriptors[22] =
{
  {
    "ID",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Pb__Request, has_id),
    offsetof(Pb__Request, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Time",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Pb__Request, has_time),
    offsetof(Pb__Request, time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Method",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Pb__Request, has_method),
    offsetof(Pb__Request, method),
    &pb__restmethod__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "BaseDn",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__Request, basedn),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Filter",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__Request, filter),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Attributes",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Pb__Request, n_attributes),
    offsetof(Pb__Request, attributes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Scope",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Pb__Request, has_scope),
    offsetof(Pb__Request, scope),
    &pb__search_scope__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Entry",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Pb__Request, entry),
    &pb__entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Dn",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__Request, dn),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Recursive",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Pb__Request, has_recursive),
    offsetof(Pb__Request, recursive),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "DerefAliases",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Pb__Request, has_derefaliases),
    offsetof(Pb__Request, derefaliases),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "SizeLimit",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Pb__Request, has_sizelimit),
    offsetof(Pb__Request, sizelimit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "TimeLimit",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Pb__Request, has_timelimit),
    offsetof(Pb__Request, timelimit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "TypesOnly",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Pb__Request, has_typesonly),
    offsetof(Pb__Request, typesonly),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ControlString",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Pb__Request, controlstring),
    &pb__control_type_string__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "GID",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Pb__Request, has_gid),
    offsetof(Pb__Request, gid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "TID",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Pb__Request, has_tid),
    offsetof(Pb__Request, tid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "TxMethod",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Pb__Request, has_txmethod),
    offsetof(Pb__Request, txmethod),
    &pb__tx_method__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ApplicationName",
    19,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__Request, applicationname),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ApplicationMethod",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__Request, applicationmethod),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ApplicationVersion",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Pb__Request, has_applicationversion),
    offsetof(Pb__Request, applicationversion),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ApplicationPayload",
    22,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__Request, applicationpayload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb__request__field_indices_by_name[] = {
  19,   /* field[19] = ApplicationMethod */
  18,   /* field[18] = ApplicationName */
  21,   /* field[21] = ApplicationPayload */
  20,   /* field[20] = ApplicationVersion */
  5,   /* field[5] = Attributes */
  3,   /* field[3] = BaseDn */
  14,   /* field[14] = ControlString */
  10,   /* field[10] = DerefAliases */
  8,   /* field[8] = Dn */
  7,   /* field[7] = Entry */
  4,   /* field[4] = Filter */
  15,   /* field[15] = GID */
  0,   /* field[0] = ID */
  2,   /* field[2] = Method */
  9,   /* field[9] = Recursive */
  6,   /* field[6] = Scope */
  11,   /* field[11] = SizeLimit */
  16,   /* field[16] = TID */
  1,   /* field[1] = Time */
  12,   /* field[12] = TimeLimit */
  17,   /* field[17] = TxMethod */
  13,   /* field[13] = TypesOnly */
};
static const ProtobufCIntRange pb__request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 22 }
};
const ProtobufCMessageDescriptor pb__request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb.Request",
  "Request",
  "Pb__Request",
  "pb",
  sizeof(Pb__Request),
  22,
  pb__request__field_descriptors,
  pb__request__field_indices_by_name,
  1,  pb__request__number_ranges,
  (ProtobufCMessageInit) pb__request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pb__tx_request__field_descriptors[3] =
{
  {
    "ID",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Pb__TxRequest, has_id),
    offsetof(Pb__TxRequest, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Time",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Pb__TxRequest, has_time),
    offsetof(Pb__TxRequest, time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Requests",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Pb__TxRequest, n_requests),
    offsetof(Pb__TxRequest, requests),
    &pb__request__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb__tx_request__field_indices_by_name[] = {
  0,   /* field[0] = ID */
  2,   /* field[2] = Requests */
  1,   /* field[1] = Time */
};
static const ProtobufCIntRange pb__tx_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor pb__tx_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb.TxRequest",
  "TxRequest",
  "Pb__TxRequest",
  "pb",
  sizeof(Pb__TxRequest),
  3,
  pb__tx_request__field_descriptors,
  pb__tx_request__field_indices_by_name,
  1,  pb__tx_request__number_ranges,
  (ProtobufCMessageInit) pb__tx_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pb__tx_response__field_descriptors[3] =
{
  {
    "ID",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Pb__TxResponse, has_id),
    offsetof(Pb__TxResponse, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "LastSuccessIndex",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Pb__TxResponse, has_lastsuccessindex),
    offsetof(Pb__TxResponse, lastsuccessindex),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Response",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Pb__TxResponse, response),
    &pb__response__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb__tx_response__field_indices_by_name[] = {
  0,   /* field[0] = ID */
  1,   /* field[1] = LastSuccessIndex */
  2,   /* field[2] = Response */
};
static const ProtobufCIntRange pb__tx_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor pb__tx_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb.TxResponse",
  "TxResponse",
  "Pb__TxResponse",
  "pb",
  sizeof(Pb__TxResponse),
  3,
  pb__tx_response__field_descriptors,
  pb__tx_response__field_indices_by_name,
  1,  pb__tx_response__number_ranges,
  (ProtobufCMessageInit) pb__tx_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pb__control_type_string__field_descriptors[3] =
{
  {
    "ControlType",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__ControlTypeString, controltype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Criticality",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Pb__ControlTypeString, has_criticality),
    offsetof(Pb__ControlTypeString, criticality),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ControlValue",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__ControlTypeString, controlvalue),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb__control_type_string__field_indices_by_name[] = {
  0,   /* field[0] = ControlType */
  2,   /* field[2] = ControlValue */
  1,   /* field[1] = Criticality */
};
static const ProtobufCIntRange pb__control_type_string__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor pb__control_type_string__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb.ControlTypeString",
  "ControlTypeString",
  "Pb__ControlTypeString",
  "pb",
  sizeof(Pb__ControlTypeString),
  3,
  pb__control_type_string__field_descriptors,
  pb__control_type_string__field_indices_by_name,
  1,  pb__control_type_string__number_ranges,
  (ProtobufCMessageInit) pb__control_type_string__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pb__entry__field_descriptors[3] =
{
  {
    "Dn",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__Entry, dn),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ModDn",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Pb__Entry, has_moddn),
    offsetof(Pb__Entry, moddn),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Attributes",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Pb__Entry, n_attributes),
    offsetof(Pb__Entry, attributes),
    &pb__entry_attribute__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb__entry__field_indices_by_name[] = {
  2,   /* field[2] = Attributes */
  0,   /* field[0] = Dn */
  1,   /* field[1] = ModDn */
};
static const ProtobufCIntRange pb__entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor pb__entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb.Entry",
  "Entry",
  "Pb__Entry",
  "pb",
  sizeof(Pb__Entry),
  3,
  pb__entry__field_descriptors,
  pb__entry__field_indices_by_name,
  1,  pb__entry__number_ranges,
  (ProtobufCMessageInit) pb__entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pb__entry_attribute__field_descriptors[3] =
{
  {
    "Method",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Pb__EntryAttribute, has_method),
    offsetof(Pb__EntryAttribute, method),
    &pb__entry_method__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Name",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__EntryAttribute, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Values",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Pb__EntryAttribute, n_values),
    offsetof(Pb__EntryAttribute, values),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb__entry_attribute__field_indices_by_name[] = {
  0,   /* field[0] = Method */
  1,   /* field[1] = Name */
  2,   /* field[2] = Values */
};
static const ProtobufCIntRange pb__entry_attribute__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor pb__entry_attribute__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb.EntryAttribute",
  "EntryAttribute",
  "Pb__EntryAttribute",
  "pb",
  sizeof(Pb__EntryAttribute),
  3,
  pb__entry_attribute__field_descriptors,
  pb__entry_attribute__field_indices_by_name,
  1,  pb__entry_attribute__number_ranges,
  (ProtobufCMessageInit) pb__entry_attribute__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pb__response__field_descriptors[17] =
{
  {
    "ID",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Pb__Response, has_id),
    offsetof(Pb__Response, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "GID",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Pb__Response, has_gid),
    offsetof(Pb__Response, gid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Metadata",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Pb__Response, metadata),
    &pb__metadata__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ResultCode",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Pb__Response, has_resultcode),
    offsetof(Pb__Response, resultcode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "MatchedDn",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__Response, matcheddn),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ResultDescription",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__Response, resultdescription),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Entries",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Pb__Response, n_entries),
    offsetof(Pb__Response, entries),
    &pb__entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Referrals",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Pb__Response, n_referrals),
    offsetof(Pb__Response, referrals),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Controls",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Pb__Response, n_controls),
    offsetof(Pb__Response, controls),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "TID",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Pb__Response, has_tid),
    offsetof(Pb__Response, tid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "StreamFlag",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Pb__Response, has_streamflag),
    offsetof(Pb__Response, streamflag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "StatusCode",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Pb__Response, has_statuscode),
    offsetof(Pb__Response, statuscode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Status",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__Response, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "StatusCodeMessage",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__Response, statuscodemessage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Message",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__Response, message),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Data",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__Response, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Count",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Pb__Response, has_count),
    offsetof(Pb__Response, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb__response__field_indices_by_name[] = {
  8,   /* field[8] = Controls */
  16,   /* field[16] = Count */
  15,   /* field[15] = Data */
  6,   /* field[6] = Entries */
  1,   /* field[1] = GID */
  0,   /* field[0] = ID */
  4,   /* field[4] = MatchedDn */
  14,   /* field[14] = Message */
  2,   /* field[2] = Metadata */
  7,   /* field[7] = Referrals */
  3,   /* field[3] = ResultCode */
  5,   /* field[5] = ResultDescription */
  12,   /* field[12] = Status */
  11,   /* field[11] = StatusCode */
  13,   /* field[13] = StatusCodeMessage */
  10,   /* field[10] = StreamFlag */
  9,   /* field[9] = TID */
};
static const ProtobufCIntRange pb__response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 17 }
};
const ProtobufCMessageDescriptor pb__response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb.Response",
  "Response",
  "Pb__Response",
  "pb",
  sizeof(Pb__Response),
  17,
  pb__response__field_descriptors,
  pb__response__field_indices_by_name,
  1,  pb__response__number_ranges,
  (ProtobufCMessageInit) pb__response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pb__metadata__field_descriptors[4] =
{
  {
    "NodeID",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Pb__Metadata, has_nodeid),
    offsetof(Pb__Metadata, nodeid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ClusterID",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Pb__Metadata, has_clusterid),
    offsetof(Pb__Metadata, clusterid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "RaftIndex",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Pb__Metadata, has_raftindex),
    offsetof(Pb__Metadata, raftindex),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "RaftTerm",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Pb__Metadata, has_raftterm),
    offsetof(Pb__Metadata, raftterm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb__metadata__field_indices_by_name[] = {
  1,   /* field[1] = ClusterID */
  0,   /* field[0] = NodeID */
  2,   /* field[2] = RaftIndex */
  3,   /* field[3] = RaftTerm */
};
static const ProtobufCIntRange pb__metadata__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor pb__metadata__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb.Metadata",
  "Metadata",
  "Pb__Metadata",
  "pb",
  sizeof(Pb__Metadata),
  4,
  pb__metadata__field_descriptors,
  pb__metadata__field_indices_by_name,
  1,  pb__metadata__number_ranges,
  (ProtobufCMessageInit) pb__metadata__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue pb__search_scope__enum_values_by_number[3] =
{
  { "BaseObject", "PB__SEARCH_SCOPE__BaseObject", 0 },
  { "SingleLevel", "PB__SEARCH_SCOPE__SingleLevel", 1 },
  { "Subtree", "PB__SEARCH_SCOPE__Subtree", 2 },
};
static const ProtobufCIntRange pb__search_scope__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex pb__search_scope__enum_values_by_name[3] =
{
  { "BaseObject", 0 },
  { "SingleLevel", 1 },
  { "Subtree", 2 },
};
const ProtobufCEnumDescriptor pb__search_scope__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "pb.SearchScope",
  "SearchScope",
  "Pb__SearchScope",
  "pb",
  3,
  pb__search_scope__enum_values_by_number,
  3,
  pb__search_scope__enum_values_by_name,
  1,
  pb__search_scope__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue pb__restmethod__enum_values_by_number[7] =
{
  { "UNKNOWN", "PB__RESTMETHOD__UNKNOWN", 0 },
  { "GET", "PB__RESTMETHOD__GET", 1 },
  { "PUT", "PB__RESTMETHOD__PUT", 2 },
  { "POST", "PB__RESTMETHOD__POST", 3 },
  { "DELETE", "PB__RESTMETHOD__DELETE", 4 },
  { "SYNC", "PB__RESTMETHOD__SYNC", 5 },
  { "QGET", "PB__RESTMETHOD__QGET", 6 },
};
static const ProtobufCIntRange pb__restmethod__value_ranges[] = {
{0, 0},{0, 7}
};
static const ProtobufCEnumValueIndex pb__restmethod__enum_values_by_name[7] =
{
  { "DELETE", 4 },
  { "GET", 1 },
  { "POST", 3 },
  { "PUT", 2 },
  { "QGET", 6 },
  { "SYNC", 5 },
  { "UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor pb__restmethod__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "pb.RESTMethod",
  "RESTMethod",
  "Pb__RESTMethod",
  "pb",
  7,
  pb__restmethod__enum_values_by_number,
  7,
  pb__restmethod__enum_values_by_name,
  1,
  pb__restmethod__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue pb__entry_method__enum_values_by_number[5] =
{
  { "Unknown", "PB__ENTRY_METHOD__Unknown", 0 },
  { "Add", "PB__ENTRY_METHOD__Add", 1 },
  { "Replace", "PB__ENTRY_METHOD__Replace", 2 },
  { "Delete", "PB__ENTRY_METHOD__Delete", 3 },
  { "Increase", "PB__ENTRY_METHOD__Increase", 4 },
};
static const ProtobufCIntRange pb__entry_method__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex pb__entry_method__enum_values_by_name[5] =
{
  { "Add", 1 },
  { "Delete", 3 },
  { "Increase", 4 },
  { "Replace", 2 },
  { "Unknown", 0 },
};
const ProtobufCEnumDescriptor pb__entry_method__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "pb.EntryMethod",
  "EntryMethod",
  "Pb__EntryMethod",
  "pb",
  5,
  pb__entry_method__enum_values_by_number,
  5,
  pb__entry_method__enum_values_by_name,
  1,
  pb__entry_method__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue pb__tx_method__enum_values_by_number[8] =
{
  { "TXUNKNOWN", "PB__TX_METHOD__TXUNKNOWN", 0 },
  { "TXBEGIN", "PB__TX_METHOD__TXBEGIN", 1 },
  { "TXDO", "PB__TX_METHOD__TXDO", 2 },
  { "TXCOMMIT", "PB__TX_METHOD__TXCOMMIT", 3 },
  { "TXROLLBACK", "PB__TX_METHOD__TXROLLBACK", 4 },
  { "TXUNDO", "PB__TX_METHOD__TXUNDO", 5 },
  { "TXLOCK", "PB__TX_METHOD__TXLOCK", 6 },
  { "TXSTORE", "PB__TX_METHOD__TXSTORE", 7 },
};
static const ProtobufCIntRange pb__tx_method__value_ranges[] = {
{0, 0},{0, 8}
};
static const ProtobufCEnumValueIndex pb__tx_method__enum_values_by_name[8] =
{
  { "TXBEGIN", 1 },
  { "TXCOMMIT", 3 },
  { "TXDO", 2 },
  { "TXLOCK", 6 },
  { "TXROLLBACK", 4 },
  { "TXSTORE", 7 },
  { "TXUNDO", 5 },
  { "TXUNKNOWN", 0 },
};
const ProtobufCEnumDescriptor pb__tx_method__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "pb.TxMethod",
  "TxMethod",
  "Pb__TxMethod",
  "pb",
  8,
  pb__tx_method__enum_values_by_number,
  8,
  pb__tx_method__enum_values_by_name,
  1,
  pb__tx_method__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
