/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: helloworld.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "helloworld.pb-c.h"
void   helloworld__hello_request__init
                     (Helloworld__HelloRequest         *message)
{
  static Helloworld__HelloRequest init_value = HELLOWORLD__HELLO_REQUEST__INIT;
  *message = init_value;
}
size_t helloworld__hello_request__get_packed_size
                     (const Helloworld__HelloRequest *message)
{
  assert(message->base.descriptor == &helloworld__hello_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t helloworld__hello_request__pack
                     (const Helloworld__HelloRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &helloworld__hello_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t helloworld__hello_request__pack_to_buffer
                     (const Helloworld__HelloRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &helloworld__hello_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Helloworld__HelloRequest *
       helloworld__hello_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Helloworld__HelloRequest *)
     protobuf_c_message_unpack (&helloworld__hello_request__descriptor,
                                allocator, len, data);
}
void   helloworld__hello_request__free_unpacked
                     (Helloworld__HelloRequest *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &helloworld__hello_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   helloworld__hello_reply__init
                     (Helloworld__HelloReply         *message)
{
  static Helloworld__HelloReply init_value = HELLOWORLD__HELLO_REPLY__INIT;
  *message = init_value;
}
size_t helloworld__hello_reply__get_packed_size
                     (const Helloworld__HelloReply *message)
{
  assert(message->base.descriptor == &helloworld__hello_reply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t helloworld__hello_reply__pack
                     (const Helloworld__HelloReply *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &helloworld__hello_reply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t helloworld__hello_reply__pack_to_buffer
                     (const Helloworld__HelloReply *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &helloworld__hello_reply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Helloworld__HelloReply *
       helloworld__hello_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Helloworld__HelloReply *)
     protobuf_c_message_unpack (&helloworld__hello_reply__descriptor,
                                allocator, len, data);
}
void   helloworld__hello_reply__free_unpacked
                     (Helloworld__HelloReply *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &helloworld__hello_reply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor helloworld__hello_request__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Helloworld__HelloRequest, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned helloworld__hello_request__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange helloworld__hello_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor helloworld__hello_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "helloworld.HelloRequest",
  "HelloRequest",
  "Helloworld__HelloRequest",
  "helloworld",
  sizeof(Helloworld__HelloRequest),
  1,
  helloworld__hello_request__field_descriptors,
  helloworld__hello_request__field_indices_by_name,
  1,  helloworld__hello_request__number_ranges,
  (ProtobufCMessageInit) helloworld__hello_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor helloworld__hello_reply__field_descriptors[1] =
{
  {
    "message",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Helloworld__HelloReply, message),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned helloworld__hello_reply__field_indices_by_name[] = {
  0,   /* field[0] = message */
};
static const ProtobufCIntRange helloworld__hello_reply__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor helloworld__hello_reply__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "helloworld.HelloReply",
  "HelloReply",
  "Helloworld__HelloReply",
  "helloworld",
  sizeof(Helloworld__HelloReply),
  1,
  helloworld__hello_reply__field_descriptors,
  helloworld__hello_reply__field_indices_by_name,
  1,  helloworld__hello_reply__number_ranges,
  (ProtobufCMessageInit) helloworld__hello_reply__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor helloworld__greeter__method_descriptors[1] =
{
  { "SayHello", &helloworld__hello_request__descriptor, &helloworld__hello_reply__descriptor },
};
const unsigned helloworld__greeter__method_indices_by_name[] = {
  0         /* SayHello */
};
const ProtobufCServiceDescriptor helloworld__greeter__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "helloworld.Greeter",
  "Greeter",
  "Helloworld__Greeter",
  "helloworld",
  1,
  helloworld__greeter__method_descriptors,
  helloworld__greeter__method_indices_by_name
};
void helloworld__greeter__say_hello(ProtobufCService *service,
                                    const Helloworld__HelloRequest *input,
                                    Helloworld__HelloReply_Closure closure,
                                    void *closure_data)
{
  assert(service->descriptor == &helloworld__greeter__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void helloworld__greeter__init (Helloworld__Greeter_Service *service,
                                Helloworld__Greeter_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &helloworld__greeter__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
